name: base
channels:
  - defaults
  - conda-forge
  - pip:
    - arviz==0.9.0
    - emcee==3.0.2
    - getdist==1.1.2
    - h5py==2.10.0
    - jax==0.2.7
    - jaxlib==0.1.57+cuda101
    - jsonschema==3.2.0
    - jupyter-live-graph==0.1.0
    - jupyterplot==0.0.3
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - mpi4py==3.0.3
    - pystan==2.19.1.1
    - pyyaml==5.3.1
    - tensor2tensor==1.15.7
    - tensorboard==1.15.0
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==1.15.5
    - tensorflow-addons==0.6.0
    - tensorflow-cpu==1.15.0
    - tensorflow-datasets==3.2.1
    - tensorflow-estimator==1.15.1
    - tensorflow-gan==2.0.0
    - tensorflow-hub==0.12.0
    - tensorflow-metadata==0.30.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - tf-slim==1.1.0
    - tqdm==4.60.0

